# Generated by Django 4.1.7 on 2023-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('unloading', 'Unloading'), ('loading', 'Loading')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
