# Generated by Django 4.1.7 on 2023-04-01 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0002_trailers_registration_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailers',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trailers_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trucks',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trucks_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
